function model(input) {
    let out = input;
    out = conv1(out);
    out = bn1(out);
    let saved = out = relu(out);

    out = layer1_0_conv1(out);
    out = layer1_0_bn1(out);
    out = relu(out);
    out = layer1_0_conv2(out);
    out = layer1_0_bn2(out);
    out = shortcut(out, [16, 32, 32], saved, [16, 32, 32]);
    saved = out = relu(out);
    out = layer1_1_conv1(out);
    out = layer1_1_bn1(out);
    out = relu(out);
    out = layer1_1_conv2(out);
    out = layer1_1_bn2(out);
    out = shortcut(out, [16, 32, 32], saved, [16, 32, 32]);
    saved = out = relu(out);
    out = layer1_2_conv1(out);
    out = layer1_2_bn1(out);
    out = relu(out);
    out = layer1_2_conv2(out);
    out = layer1_2_bn2(out);
    out = shortcut(out, [16, 32, 32], saved, [16, 32, 32]);
    saved = out = relu(out);
    out = layer1_3_conv1(out);
    out = layer1_3_bn1(out);
    out = relu(out);
    out = layer1_3_conv2(out);
    out = layer1_3_bn2(out);
    out = shortcut(out, [16, 32, 32], saved, [16, 32, 32]);
    saved = out = relu(out);
    out = layer1_4_conv1(out);
    out = layer1_4_bn1(out);
    out = relu(out);
    out = layer1_4_conv2(out);
    out = layer1_4_bn2(out);
    out = shortcut(out, [16, 32, 32], saved, [16, 32, 32]);
    saved = out = relu(out);
    out = layer1_5_conv1(out);
    out = layer1_5_bn1(out);
    out = relu(out);
    out = layer1_5_conv2(out);
    out = layer1_5_bn2(out);
    out = shortcut(out, [16, 32, 32], saved, [16, 32, 32]);
    saved = out = relu(out);
    out = layer1_6_conv1(out);
    out = layer1_6_bn1(out);
    out = relu(out);
    out = layer1_6_conv2(out);
    out = layer1_6_bn2(out);
    out = shortcut(out, [16, 32, 32], saved, [16, 32, 32]);
    saved = out = relu(out);
    out = layer1_7_conv1(out);
    out = layer1_7_bn1(out);
    out = relu(out);
    out = layer1_7_conv2(out);
    out = layer1_7_bn2(out);
    out = shortcut(out, [16, 32, 32], saved, [16, 32, 32]);
    saved = out = relu(out);
    out = layer1_8_conv1(out);
    out = layer1_8_bn1(out);
    out = relu(out);
    out = layer1_8_conv2(out);
    out = layer1_8_bn2(out);
    out = shortcut(out, [16, 32, 32], saved, [16, 32, 32]);
    saved = out = relu(out);
    out = layer2_0_conv1(out);
    out = layer2_0_bn1(out);
    out = relu(out);
    out = layer2_0_conv2(out);
    out = layer2_0_bn2(out);
    out = shortcut(out, [32, 16, 16], saved, [16, 32, 32]);
    saved = out = relu(out);
    out = layer2_1_conv1(out);
    out = layer2_1_bn1(out);
    out = relu(out);
    out = layer2_1_conv2(out);
    out = layer2_1_bn2(out);
    out = shortcut(out, [32, 16, 16], saved, [32, 16, 16]);
    saved = out = relu(out);
    out = layer2_2_conv1(out);
    out = layer2_2_bn1(out);
    out = relu(out);
    out = layer2_2_conv2(out);
    out = layer2_2_bn2(out);
    out = shortcut(out, [32, 16, 16], saved, [32, 16, 16]);
    saved = out = relu(out);
    out = layer2_3_conv1(out);
    out = layer2_3_bn1(out);
    out = relu(out);
    out = layer2_3_conv2(out);
    out = layer2_3_bn2(out);
    out = shortcut(out, [32, 16, 16], saved, [32, 16, 16]);
    saved = out = relu(out);
    out = layer2_4_conv1(out);
    out = layer2_4_bn1(out);
    out = relu(out);
    out = layer2_4_conv2(out);
    out = layer2_4_bn2(out);
    out = shortcut(out, [32, 16, 16], saved, [32, 16, 16]);
    saved = out = relu(out);
    out = layer2_5_conv1(out);
    out = layer2_5_bn1(out);
    out = relu(out);
    out = layer2_5_conv2(out);
    out = layer2_5_bn2(out);
    out = shortcut(out, [32, 16, 16], saved, [32, 16, 16]);
    saved = out = relu(out);
    out = layer2_6_conv1(out);
    out = layer2_6_bn1(out);
    out = relu(out);
    out = layer2_6_conv2(out);
    out = layer2_6_bn2(out);
    out = shortcut(out, [32, 16, 16], saved, [32, 16, 16]);
    saved = out = relu(out);
    out = layer2_7_conv1(out);
    out = layer2_7_bn1(out);
    out = relu(out);
    out = layer2_7_conv2(out);
    out = layer2_7_bn2(out);
    out = shortcut(out, [32, 16, 16], saved, [32, 16, 16]);
    saved = out = relu(out);
    out = layer2_8_conv1(out);
    out = layer2_8_bn1(out);
    out = relu(out);
    out = layer2_8_conv2(out);
    out = layer2_8_bn2(out);
    out = shortcut(out, [32, 16, 16], saved, [32, 16, 16]);
    saved = out = relu(out);
    out = layer3_0_conv1(out);
    out = layer3_0_bn1(out);
    out = relu(out);
    out = layer3_0_conv2(out);
    out = layer3_0_bn2(out);
    out = shortcut(out, [64, 8, 8], saved, [32, 16, 16]);
    saved = out = relu(out);
    out = layer3_1_conv1(out);
    out = layer3_1_bn1(out);
    out = relu(out);
    out = layer3_1_conv2(out);
    out = layer3_1_bn2(out);
    out = shortcut(out, [64, 8, 8], saved, [64, 8, 8]);
    saved = out = relu(out);
    out = layer3_2_conv1(out);
    out = layer3_2_bn1(out);
    out = relu(out);
    out = layer3_2_conv2(out);
    out = layer3_2_bn2(out);
    out = shortcut(out, [64, 8, 8], saved, [64, 8, 8]);
    saved = out = relu(out);
    out = layer3_3_conv1(out);
    out = layer3_3_bn1(out);
    out = relu(out);
    out = layer3_3_conv2(out);
    out = layer3_3_bn2(out);
    out = shortcut(out, [64, 8, 8], saved, [64, 8, 8]);
    saved = out = relu(out);
    out = layer3_4_conv1(out);
    out = layer3_4_bn1(out);
    out = relu(out);
    out = layer3_4_conv2(out);
    out = layer3_4_bn2(out);
    out = shortcut(out, [64, 8, 8], saved, [64, 8, 8]);
    saved = out = relu(out);
    out = layer3_5_conv1(out);
    out = layer3_5_bn1(out);
    out = relu(out);
    out = layer3_5_conv2(out);
    out = layer3_5_bn2(out);
    out = shortcut(out, [64, 8, 8], saved, [64, 8, 8]);
    saved = out = relu(out);
    out = layer3_6_conv1(out);
    out = layer3_6_bn1(out);
    out = relu(out);
    out = layer3_6_conv2(out);
    out = layer3_6_bn2(out);
    out = shortcut(out, [64, 8, 8], saved, [64, 8, 8]);
    saved = out = relu(out);
    out = layer3_7_conv1(out);
    out = layer3_7_bn1(out);
    out = relu(out);
    out = layer3_7_conv2(out);
    out = layer3_7_bn2(out);
    out = shortcut(out, [64, 8, 8], saved, [64, 8, 8]);
    saved = out = relu(out);
    out = layer3_8_conv1(out);
    out = layer3_8_bn1(out);
    out = relu(out);
    out = layer3_8_conv2(out);
    out = layer3_8_bn2(out);
    out = shortcut(out, [64, 8, 8], saved, [64, 8, 8]);
    out = relu(out);

    out = channelWiseMean(out, 64, 8, 8)
    out = linear(out)

    return argmax(out);
}